CREATE TABLE TBL_PLAYER_INFO (
 	REGIST_CODE CHAR(4) NOT NULL PRIMARY KEY,
 	NAME VARCHAR(18),
 	BIRTH_DAY VARCHAR(8),
 	HEIGHT NUMBER(3),
 	WEIGHT NUMBER(3)
);
 
INSERT INTO TBL_PLAYER_INFO VALUES('A001','김길동','19900101', 180, 82);
INSERT INTO TBL_PLAYER_INFO VALUES('A005','이길동','20000101', 190, 85);
INSERT INTO TBL_PLAYER_INFO VALUES('B002','홍길동','19950101', 175, 75);
INSERT INTO TBL_PLAYER_INFO VALUES('B006','조길동','19990101', 185, 80);

SELECT * FROM TBL_PLAYER_INFO

CREATE TABLE TBL_HITTER_INFO(
	REGIST_CODE CHAR(4) NOT NULL PRIMARY KEY,
	GAME_NUMBERS NUMBER(3),
	APPEARANCE NUMBER(3),
	HIT_NUMBERS	NUMBER(3),
	HOME_RUNS NUMBER(3),
	PUT_OUT	NUMBER(3),
	DOUBLE_PLAY	NUMBER(3),
	ERROR_COUNT	NUMBER(3)
);

INSERT INTO TBL_HITTER_INFO VALUES('A001', 120, 330, 100, 20, 80, 27, 1);
INSERT INTO TBL_HITTER_INFO VALUES('A005', 110, 300, 110, 30, 60, 5, 2);
INSERT INTO TBL_HITTER_INFO VALUES('B002', 100, 270, 90, 5, 100, 10, 3);

SELECT * FROM TBL_HITTER_INFO


--9쪽 타자 선택 화면에 나오는 코드, 이름
SELECT REGIST_CODE, NAME FROM TBL_PLAYER_INFO;

--9쪽 등록 버튼 => 타자 성적 테이블 (8개 값)
INSERT INTO TBL_HITTER_INFO VALUES('B002', 100, 270, 90, 5, 100, 10, 3);
INSERT INTO TBL_HITTER_INFO VALUES(?, ?, ?, ?, ?, ?, ?, ?);


--13~15쪽 개별 타자 성적 조회
SELECT
	P.REGIST_CODE, P.NAME,
	H.GAME_NUMBERS, H.APPEARANCE, H.HIT_NUMBERS, H.HOME_RUNS,
	ROUND( ((HIT_NUMBERS+HOME_RUNS)/APPEARANCE * 100 + HOME_RUNS), 2) AS ATTACK,
	H.PUT_OUT, H.DOUBLE_PLAY, H.ERROR_COUNT,
	(PUT_OUT+(DOUBLE_PLAY*2) - (ERROR_COUNT*5)) AS DEFENCE
FROM TBL_HITTER_INFO H
JOIN TBL_PLAYER_INFO P ON P.REGIST_CODE=H.REGIST_CODE
WHERE H.REGIST_CODE = 'A001';

--16 전체 타자 조회
SELECT
	REGIST_CODE ,
 	NAME,
 	BIRTH_DAY,
 	HEIGHT,
 	WEIGHT,
 	--(ATTACK+DEFENCE)/2 AS SCORE,
 	CASE
 		WHEN (ATTACK+DEFENCE)/2 >=90 THEN 'A'
 		WHEN (ATTACK+DEFENCE)/2 >=80 THEN 'B'
 		WHEN (ATTACK+DEFENCE)/2 >=70 THEN 'C'
 		WHEN (ATTACK+DEFENCE)/2 >=60 THEN 'D'
 		ELES 'E'
 	END AS GRADE,
 	RANK() OVER(ORDER BY (ATTACK+DEFENCE)/2 DESC) AS RANK
 	
FROM(
SELECT
 	P.REGIST_CODE ,
 	P.NAME,
 	P.BIRTH_DAY,
 	P.HEIGHT,
 	P.WEIGHT,
 	ROUND( ((HIT_NUMBERS+HOME_RUNS)/APPEARANCE * 100 + HOME_RUNS), 2) AS ATTACK,
 	(PUT_OUT+(DOUBLE_PLAY*2) - (ERROR_COUNT*5)) AS DEFENCE
FROM TBL_HITTER_INFO H
JOIN TBL_PLAYER_INFO P ON P.REGIST_CODE=H.REGIST_CODE
);